<a href="https://colab.research.google.com/github/Khey17/100-Days-Of-ML-Code/blob/main/TensorFlow_Fundamentals_00.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stuff to cover in TensorFlow

- TensorFlow Basics & Fundamentals
- Preprocessing Data (getting it into tensors)
- Building and using pretrained deep learning models
- Fitting a model to the data (learning patterns)
- Making predictions with a model (using patterns)
- Evaluating model predictions
- Saving and Loading models
- Using a trained model to make predictions on custom data


In [1]:
print('Start Session!')

# Motto 1: 'If in doubt, run the code'
# Motto 2: 'Experiment -> repeat'
# Motto 3: 'Visualize -> repeat'
# Motto 4: 'Ask Questions (incl the dumb ones)'

# Things to AVOID!
# Overthinking


Start Session!


# WorkFlow
## 1. Get data ready
(turn into tensors)
## 2. Build or pick a pretrained model
(to suit your problem)
## 3. Fit the model to make the data and make a prediction
## 4. Evaluate the model
## 5. Improve through experimentation
## 6. Save and reload your trained model


# In this Notebook, we're going to cover some of the most fundamental concepts of tensors using TensorFlow
More specifically, we're going to cover:
- Introduction to tensors
- Getting information from tensors
- Manipulating tensors
- Tensors & NumPy
- Using @tf.function(way to speed up your regular python functions)
- Using GPUs with TensorFlow (or TPUs)
- Exercises

## 1. Get data ready

### Introduction to Tensors

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check the dimensions of our vector
vector.ndim

1

In [7]:
# Create a Matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 7.],
                              [8., 9.]], dtype=tf.float16) # Specify the data type with dtype param
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  7.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
# What's the number of dimensions of another_matrix
another_matrix.ndim

2

In [11]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [12]:
tensor.ndim # 3 dimensions

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction (e.g. wind speed and direction)
* Matrix: a 2-D array of numbers
* Tensor: an n-dimensional array of numbers (where n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

### Creating tensors with tf.Variable

In [17]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Let's try changing one of the elements in our changeable tensor
changeable_tensor[0] = tf.constant(15)
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
changeable_tensor[0].assign(tf.constant(15))
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15,  7], dtype=int32)>

In [20]:
# Let's try to change our unchangeable tensor
unchangeable_tensor[0].assign(tf.constant(15))
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

🔑**Note**: Rarely in practice will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However, if in doubt, use tf.constant and change it later if needed

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers

In [21]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [22]:
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [23]:
# Are they equal?
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

### Shuffle the order of elements in tensor

In [24]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't get affected)
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
tf.random.set_seed(42) # global level random seed
not_shuffled, tf.random.shuffle(not_shuffled, seed=42)

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>)

📑**Exercise:** Read through the TensorFlow documentation on [Random-Seed]('https://www.tensorflow.org/api_docs/python/tf/random/set_seed')

### Other ways to create tensors

In [25]:
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [26]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### You can also turn NumPy array into Tensors

The main difference b/w NumPy arrays and Tensors is that tensors can be run on GPU for faster computing

In [27]:
# Turning Numpy array into Tensors
import numpy as np

numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

# X = tf.constant(some_matriz) # capital for matrix or tensor
# Y = tf.constant(vector) # none-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [28]:
A = tf.constant(numpy_A, shape=(3, 8)) # 2, 3, 4
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from Tensors

* Shape
* Rank
* Axis or dimension
* Size

In [29]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [31]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [32]:
# Get various attributes of our tensor
print('DataType of every element: ', rank_4_tensor.dtype)
print('Number of Dimensions (rank) : ', rank_4_tensor.ndim)
print('Total number of elements along 0 axis: ', rank_4_tensor.shape[0])
print('Total number of elements along 1 axis: ', rank_4_tensor.shape[1])
print('Total number of elements along 2 axis: ', rank_4_tensor.shape[2])
print('Total number of elements along 3 axis: ', rank_4_tensor.shape[3])
print('Total number of elements (for flattened tensor): ', tf.size(rank_4_tensor).numpy())

DataType of every element:  <dtype: 'float32'>
Number of Dimensions (rank) :  4
Total number of elements along 0 axis:  2
Total number of elements along 1 axis:  3
Total number of elements along 2 axis:  4
Total number of elements along 3 axis:  5
Total number of elements (for flattened tensor):  120


### Indexing Tensors
Tensors can be indexed just like Python lists

In [33]:
some_list = [1, 2 ,3, 4]
some_list[:2]

[1, 2]

In [34]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [35]:
some_list[:1]

[1]

In [36]:
# Get the first element from each dimension from each index except the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [38]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_4_tensor.ndim

(TensorShape([2, 2]), 4)

In [39]:
some_list, some_list[-1]

([1, 2, 3, 4], 4)

In [40]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [41]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[:, :, tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [42]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [43]:
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

### Manipulating Tensors (tensor operations)
**Basic Operations**
`+`, `-`, `*`, `/`

In [44]:
# You can add values to a tensor using the additions operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [45]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [46]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [47]:
# Subtraction if you want
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [48]:
# We can use the tensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

🔑**Note:** tf operations are faster than python operators like `*`

**Matrix Multiplication**

In Machine Learning, matrix multiplication is one of the most common tensor operations.

There are two rules our tensors (or matrices) need to fullfil if we're going to matrix multiply them:
1. The inner dimensions must match
2. The resulting matrix has the shape of the inner dimensions

In [49]:
# Matrix Multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [50]:
# Matrix multiplication with python operator '@'
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [51]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [52]:
tensor.shape

TensorShape([2, 2])

In [53]:
# Create a tensor (3, 2)
X = tf.constant([[1, 2],
                      [3, 4],
                      [5, 6]])
# Create another tensor (3, 2)
Y = tf.constant([[7, 8],
                      [9, 10],
                      [11, 12]])
# Matrix Multiplication
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [54]:
# Try to matrix multiply tensors of same shape
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

📖**Resource:** Info and example of [matrix multiplication](https://www.mathsisfun.com/algebra/matrix-multiplying.html)

In [55]:
# Let's change the shape of Y
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [56]:
# Let's try change the shape of X
tf.matmul(tf.reshape(X, (2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [57]:
# Can do the same with transpose
X, tf.transpose(X), tf.reshape(X, (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [58]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(X, tf.transpose(Y)), tf.matmul(tf.transpose(X), Y)

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

**The Dot Product**

Matrix Multiplication is also referred to as the dot product.

You can perform matrix multiplication using:
- `tf.matmul()`
- `tf.tensordot()`

In [59]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [60]:
# Perform matrix multiplication between X and Y (transpose Y)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [61]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
# Check the values of Y, reshape Y and transposed Y
print('Normal:\n', Y)
print()
print('Reshaped:\n', tf.reshape(Y, (2, 3)))
print()
print('Transposed:\n', tf.transpose(Y))

Normal:
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

Reshaped:
 tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)

Transposed:
 tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally, when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to get satisfy the matrix multiplication rules

### Changing the datatype of a tensor

In [65]:
tf.__version__

'2.15.0'

In [66]:
# Create a new tensor with default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [67]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [68]:
# Change from float32 to float16 (reduced precision)
tf.cast(B, tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [69]:
# Change from int32 to float32
E = tf.cast(C, tf.float32)
E.dtype

tf.float32

In [70]:
tf.cast(E, tf.float16)

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = considering them from multiple values down to a smaller amount values.

In [71]:
# Get the absolute values
D = tf.constant([-7, -10])
D, tf.abs(D)

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

Let's go through the following forms of aggregation:
- Get the sum of all values
- Get the mean of all values
- Get the minimum value
- Get the maximum value

In [72]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([18, 28, 70, 76,  6,  1, 65, 46, 76, 71, 28, 87,  3, 56, 98, 32, 36,
       79, 99, 97, 73, 62, 91,  5, 31, 57, 40, 12, 60, 84,  5,  2, 98, 82,
        0, 30, 46, 15, 93, 42, 77, 61,  2, 55, 77, 49, 26, 72, 19, 61])>

In [73]:
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [74]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [75]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [76]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=49>

In [77]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2499>

📑**Exercise:** With what we've just learned, find the variance and standard deviation of the tensor using tf methods.

In [78]:
# Find the variance
F = tf.cast(E, tf.float32)
print(tf.math.reduce_variance(F))

# Or
import tensorflow_probability as tfp
tfp.stats.variance(E)

tf.Tensor(960.0595, shape=(), dtype=float32)


<tf.Tensor: shape=(), dtype=int64, numpy=961>

In [79]:
# Find the std
tf.math.reduce_std(F), tf.math.reduce_std(tf.cast(E, tf.float32))

(<tf.Tensor: shape=(), dtype=float32, numpy=30.984827>,
 <tf.Tensor: shape=(), dtype=float32, numpy=30.984827>)

### Find the positional maximum and minimum

In [80]:
# Create a new tensor for finding positional max and min
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [81]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [82]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [83]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [84]:
# Equality Check
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [85]:
tf.reduce_min(F), tf.argmin(F), F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

### Squeezing a tensor (removing all single dimesions)

In [86]:
# Create a tensor to get started
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [87]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [88]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

### One-Hot encoding tensors

In [89]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple

# one-hot encoding the list
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list, depth=4, on_value='yo, I love deep learning?', off_value='I also like to dance')

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo, I love deep learning?', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo, I love deep learning?',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo, I love deep learning?', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo, I love deep learning?']],
      dtype=object)>

### Squaring, log, square root

In [91]:
# Create a new tensor
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [92]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [93]:
# just H causes an error
tf.sqrt(H)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt] name: 

In [94]:
# find the squareroot
tf.sqrt(tf.cast(H, tf.float32)) # just H causes an error

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [95]:
tf.math.log(tf.cast(H, tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays.

🔑**Note:** One of the main differences between a tensorflow tensor and a NumPy array is that tensor can be run on a GPU or TPU (for faster numerical processing).

In [96]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [97]:
# Convert our tensor back to numPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [98]:
# Convert tensor J to NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [99]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [100]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [101]:
### Finding access to GPUs
tf.config.list_physical_devices('GPU')

[]

🔑**Note:** If you have access to a CUDA-enabled GPU, tensorflow will automatically use it.

In [102]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### Exericise 00.

In [103]:
# Task 1 & 2
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
# Find the shape, rank and size of the tensors you created in 1.
vec = tf.constant([1., 2., 3.])
sc = tf.constant(2.)
matrix = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])
tensor = tf.constant([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]])

tf.shape(tensor), tf.rank(tensor), tf.size(tensor)  # shape, rank, size

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=9>)

In [105]:
# Task 3, 4, and 5
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
# Multiply the two tensors you created in 3 using matrix multiplication.
# Multiply the two tensors you created in 3 using dot product.
t1 = tf.random.uniform([5, 300], 0, 1)
t2 = tf.random.uniform([5, 300], 0, 1)
t1, t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7413678 , 0.62854624, 0.01738465, ..., 0.4851334 , 0.21059811,
         0.25082767],
        [0.10842848, 0.48783147, 0.8240961 , ..., 0.9204427 , 0.36046863,
         0.28176582],
        [0.7326695 , 0.46489418, 0.13622475, ..., 0.28130388, 0.63987684,
         0.9987265 ],
        [0.01447165, 0.7845044 , 0.33475304, ..., 0.56194997, 0.0209924 ,
         0.1740731 ],
        [0.90936875, 0.19861352, 0.9481231 , ..., 0.3573054 , 0.13161755,
         0.22565222]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
         0.7110305 ],
        [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
         0.06227863],
        [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
         0.44452012],
        [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
         0.47421408],
        [0.26160

In [107]:
tf.matmul(t1, tf.transpose(t2)), tf.matmul(tf.transpose(t1), t2)

(<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
 array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
        [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
        [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
        [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
        [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
       dtype=float32)>,
 <tf.Tensor: shape=(300, 300), dtype=float32, numpy=
 array([[1.0084032 , 0.71012473, 1.1784046 , ..., 0.60044616, 1.5507468 ,
         1.1868911 ],
        [0.7292022 , 1.449391  , 0.8976443 , ..., 0.47441158, 1.0954876 ,
         1.1259646 ],
        [0.4154508 , 1.0121944 , 0.37484637, ..., 0.4861176 , 1.4172977 ,
         0.6170948 ],
        ...,
        [0.66551346, 1.4914606 , 0.6736438 , ..., 0.41993898, 1.1398003 ,
         0.91970986],
        [0.4193687 , 0.6884688 , 0.6510746 , ..., 0.26083416, 0.6912869 ,
         0.51296514],
        [0.56783164, 0.9308104 , 0.99627095, ..., 0.436

In [108]:
t1 * t2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[5.48783302e-01, 2.13317230e-01, 9.89622157e-03, ...,
        4.19962183e-02, 4.14177142e-02, 1.78346112e-01],
       [1.43750124e-02, 3.96572769e-01, 1.05821081e-02, ...,
        2.48142723e-02, 1.05539955e-01, 1.75479893e-02],
       [2.07053125e-01, 2.22535610e-01, 1.05668835e-01, ...,
        7.94384107e-02, 4.04473841e-01, 4.43954021e-01],
       [2.93669698e-04, 6.15150273e-01, 5.66369221e-02, ...,
        1.46911472e-01, 9.03838966e-03, 8.25479180e-02],
       [2.37898037e-01, 1.81523582e-03, 1.92062274e-01, ...,
        1.26778647e-01, 1.30817026e-01, 7.95180276e-02]], dtype=float32)>

In [111]:
# dot product
tf.tensordot(t1, tf.transpose(t2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.63513 , 73.275154, 72.47874 , 73.895355, 77.06909 ],
       [76.148026, 77.38722 , 76.156006, 78.4779  , 77.93587 ],
       [74.061386, 75.79873 , 74.00405 , 74.954445, 74.857666],
       [72.6186  , 77.07387 , 72.674484, 75.91608 , 73.15646 ],
       [74.65547 , 76.221756, 75.43701 , 76.92053 , 76.65762 ]],
      dtype=float32)>

In [113]:
# Task 6
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
t3 = tf.random.uniform([224, 224, 3], 0, 1)
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.95831835, 0.01680839, 0.3156035 ],
        [0.16013157, 0.7148702 , 0.7892921 ],
        [0.11484027, 0.33310425, 0.21091413],
        ...,
        [0.6279857 , 0.85051286, 0.9490392 ],
        [0.62438786, 0.2802421 , 0.18754554],
        [0.9087832 , 0.46846092, 0.5317346 ]],

       [[0.85744655, 0.51288927, 0.18603599],
        [0.04882693, 0.78045344, 0.79377043],
        [0.9356363 , 0.32798207, 0.15949786],
        ...,
        [0.6933085 , 0.5420611 , 0.1860913 ],
        [0.7326596 , 0.9234495 , 0.07200372],
        [0.5471792 , 0.24985266, 0.14673471]],

       [[0.5033684 , 0.7000841 , 0.21468806],
        [0.9304948 , 0.17212296, 0.720364  ],
        [0.6657183 , 0.17304075, 0.7110392 ],
        ...,
        [0.35423398, 0.126225  , 0.24436975],
        [0.096439  , 0.06387579, 0.32836854],
        [0.15067935, 0.6084572 , 0.47766674]],

       ...,

       [[0.23573959, 0.42224514, 0.9151635 ],
        [0.38

In [120]:
# Task 7
# Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_max(t3, axis=1)[:5], tf.reduce_min(t3, axis=1)[:5]

(<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[0.97661173, 0.9950018 , 0.9879626 ],
        [0.99991286, 0.99526465, 0.9895823 ],
        [0.9881562 , 0.9997591 , 0.9961891 ],
        [0.993449  , 0.9932159 , 0.994305  ],
        [0.9981915 , 0.9879205 , 0.99483085]], dtype=float32)>,
 <tf.Tensor: shape=(5, 3), dtype=float32, numpy=
 array([[0.00023615, 0.00192714, 0.01577199],
        [0.00943911, 0.00078368, 0.00470686],
        [0.00352001, 0.01213205, 0.0098573 ],
        [0.0012126 , 0.00113928, 0.0002141 ],
        [0.001091  , 0.008641  , 0.00021005]], dtype=float32)>)

In [127]:
# Task 8
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
t4 = tf.random.uniform([1, 224, 224, 3], 0, 1)
tf.squeeze(t4, axis=0)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.76348245, 0.16075182, 0.5523535 ],
        [0.08810532, 0.69651234, 0.23381388],
        [0.92472243, 0.7419009 , 0.5493649 ],
        ...,
        [0.7639142 , 0.24412549, 0.97202635],
        [0.91811335, 0.28327274, 0.294461  ],
        [0.0991931 , 0.44304156, 0.7538786 ]],

       [[0.31252944, 0.28488004, 0.8158264 ],
        [0.5814265 , 0.7239256 , 0.95114875],
        [0.72319496, 0.14996958, 0.670864  ],
        ...,
        [0.10545242, 0.93986094, 0.8264524 ],
        [0.01470625, 0.7836441 , 0.7786864 ],
        [0.6015705 , 0.6522559 , 0.49375665]],

       [[0.1681993 , 0.41941226, 0.15349734],
        [0.58708894, 0.5825807 , 0.09037614],
        [0.12821949, 0.58877873, 0.9416256 ],
        ...,
        [0.46335363, 0.90255535, 0.1752547 ],
        [0.49124944, 0.37583804, 0.8753272 ],
        [0.32209826, 0.3392942 , 0.04181635]],

       ...,

       [[0.0073365 , 0.51613295, 0.5894784 ],
        [0.35

In [132]:
# # Task 9 and 10
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
# One-hot encode the tensor you created in 9.

t5 = tf.random.uniform([10], 0, 20, tf.int32)
t5, tf.argmax(t5), tf.one_hot(tf.argmax(t5), 10)

(<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 4,  7, 11,  4,  5, 17, 16,  4,  4,  6], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int64, numpy=5>,
 <tf.Tensor: shape=(10,), dtype=float32, numpy=array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)>)